### ISSUE TITLE
Extracted files

### ISSUE THREAD

**Issue by spinboldak** [KnugiHK/WhatsApp-Key-DB-Extractor#3]
I followed the instructions in the readme and everything went smoothly. However, i cant find the extracted files. 
Where are those saved?

**Comment by KnugiHK** [comment]
They should appear in the "[extracted](https://github.com/KnugiHK/WhatsApp-Key-DB-Extractor/tree/master/extracted)" folder.

**Comment by KnugiHK** [comment]
Possibly the same issue as #4.
