### ISSUE TITLE
0 was unexpected at this time.

### ISSUE THREAD

**Issue by ProfessorShroom** [KnugiHK/WhatsApp-Key-DB-Extractor#7]
I run the batch file, then connect my phone and I get the following error:

Please connect your Android device with USB Debugging enabled:

* daemon not running. starting it now on port 5037 *
* daemon started successfully *

0 was unexpected at this time.

**Comment by KnugiHK** [comment]
Hi. Please remove `@echo off` from the first line, then post the output again  so that we know which command cause the error.

**Comment by ProfessorShroom** [comment]
I used the powershell one instead and it work

**Comment by arcbomi** [comment]
> 我使用了 powershell 来代替，它可以工作

me too

**Comment by giuliawillcox** [comment]
I can't do it neither via batch file or power shell. no error messages are shown, the window simply closes. What can be causing this? can you help me?

**Comment by KnugiHK** [comment]
> I can't do it neither via batch file or power shell. no error messages are shown, the window simply closes. What can be causing this? can you help me?

Please share any output from your terminal. It would be a helpful starting point for troubleshooting.
